# Generated by Django 3.2.6 on 2021-09-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='note',
            fields=[
                ('nid', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=300)),
                ('img', models.ImageField(upload_to='media/')),
                ('date', models.CharField(max_length=200)),
            ],
        ),
    ]
